package com.utouu.module.login.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table t_user.
 */
public class AccountNumberBean {

    public String loginName;
    public String headUrl;

    public AccountNumberBean(String loginName, String headUrl) {
        this.loginName = loginName;
        this.headUrl = headUrl;
    }
}
